### ISSUE TITLE
stat term in output and imputed reads plot

### ISSUE THREAD

**Issue by ktyssowski** [cz-ye/DECENT#1]
Hi! I read your biorXIV paper and tried DECENT. I'm wondering what the stat column in the de.table output is. 

Also--how did you make the plot in Supplementary figure #3? Can I get the imputed reads from the output files somehow? Or is there another function I can run that is part of the package?

Thanks!

**Comment by cz-ye** [comment]
Thank you for your interest!

The stat column is obtained by taking the square root of the likelihood ratio test statistic and adding the sign of log fold change. 

The function for getting imputed data matrix is now available. Please let me know if you encounter any problems.
