### ISSUE TITLE
Capture efficiency

### ISSUE THREAD

**Issue by AlemuTA** [cz-ye/DECENT#3]
Hi,

I appreciate your method, especially the way you try to distinguish the technical and biological reasons that drive the zero inflation. I used your package to analyse my scRNA-seq data and I was mostly interested in the cell specific RNA capture efficiency.  The statistical methods you proposed to describe and estimate the CE is elegant and reasonable.  However, the package does not (if I'm correct) return the estimated CE, and the outputs seem generally restricted to testing DE (DE table). I guess it will be helpful (at least for me) in different ways if the output incorporates the CE estimates and also the estimated probability of dropout.

Can you suggest me how to extract the CE estimates from your package?

Regards,
Alemu

**Comment by cz-ye** [comment]
Thank you for your interest in our package. As for your question, apart from the returned `de.table`, there will be three files saved under the directory sepecified by `dir` argument (`'./'` by default). If you load `decent.DE.rds`, the `$CE` element will be a vector containing cell-specific capture efficiencies. Note that they are only meaningful if you used ERCC spike-ins.

Currently we do not include the probability of dropout (I suppose you mean the expected proportion of technical zeros) in the output. It is a good idea and hopeully we can add this feature in the next version.

Best,
Cz
