### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by wang950312** [cz-ye/DECENT#4]
Error in readRDS(nsInfoFilePath).
How to fix it?

**Comment by cz-ye** [comment]
We have not encountered this error before. Could you provide more information?

**Comment by wang950312** [comment]
Sorry, no special message, I just paste the example install text: `devtools::install_github("cz-ye/DECENT")`.
I want to install your package into my linux operator, maybe caused by platform?

**Comment by cz-ye** [comment]
Could be. This does not look like an error specific to our package. Perhaps you can try things like updating R.

**Comment by wang950312** [comment]
But I have successfully installed the release v0.1.0, beacause the lastest 0.99.1 failed.

**Comment by cz-ye** [comment]
This is strange. The initial version actually has more dependencies, etc. How did you install release v0.1.0?

**Comment by wang950312** [comment]
> This is strange. The initial version actually has more dependencies, etc. How did you install release v0.1.0?

I just downloaded the tar.gz file and installed from local files. And I used another computer (windows 10), v0.99.1 also failed.

**Comment by cz-ye** [comment]
I have created a v0.99.1 release. Could you try installing it locally?

**Comment by wang950312** [comment]
> I have created a v0.99.1 release. Could you try installing it locally?

Nope, the same error.

**Comment by cz-ye** [comment]
Could you: 
1. try installing v0.2.0 and see what happens?
2. provide the version of your R and the dependent packages (as listed in the NAMESPACE)?

And is this message "Error in readRDS(nsInfoFilePath)" all you get?

**Comment by wang950312** [comment]
> Could you:
> 
> 1. try installing v0.2.0 and see what happens?
> 2. provide the version of your R and the dependent packages (as listed in the NAMESPACE)?
> 
> And is this message "Error in readRDS(nsInfoFilePath)" all you get?

1. v0.2.0 also failed, but the first time to tell me that need dependent package `RcppNumerical`
2. I  used R `r-base-core_3.5.0-1xenial_amd64`, and the error messages all the same : 
```
Error in readRDS(nsInfoFilePath) : 读取链结时发生了错误
ERROR: lazy loading failed for package ‘DECENT’
```

**Comment by wang950312** [comment]
> Could you:
> 
> 1. try installing v0.2.0 and see what happens?
> 2. provide the version of your R and the dependent packages (as listed in the NAMESPACE)?
> 
> And is this message "Error in readRDS(nsInfoFilePath)" all you get?

I got it! I reinstalled the dependent packages listed NAMESPACE, and it works.
Thanks for you patiently help.

**Comment by cz-ye** [comment]
Glad it worked! And thank you for your interest in the package.
