### ISSUE TITLE
out of memory problem

### ISSUE THREAD

**Issue by huqingtao2018** [cz-ye/DECENT#5]
Hi, I read your BioRxiv paper and I'm trying DECENT for my scRNA-seq data.I encounted two problem and would you please give me some suggestions.

First, I can run the DECENT sucessfully using the test data "sim", but for some of my data it reports the following error message.
......
EM iteration 6 finished at 2019-05-29 16:28:18  Log-likelihood: 0 
Error in if ((loglik.vec[iter] - loglik.vec[iter - 1])/abs(loglik.vec[iter -  :  missing value where TRUE/FALSE needed"

Another problem is, for my large dataset (25000 gene, 10000 cell), DECENT was killed in R and the error message is out of memory. 

Would you please help me about those problems?

Thank you.
Best wishes.

**Comment by limfuxing** [comment]
Dear Huqing,
I am the co-author of DECENT package. Thanks for your interest in DECENT.
DECENT has now been accepted in Bioinformatics and it should be published
online soon. If you are interested, I can send you the accepted version.

Re: your problem:
What format is your data? Is it UMI or read-count. Strictly speaking,
DECENT was developed only for UMI data. To make it work for read count
data, I have found we need to tweak the integration bound slightly. Also,
for stable results, DECENT requires all cells to have at least 3% non-zero
count and at least 5 non-zero counts among the genes.

If you have performed the above the filtering and the problem persists,
you need to use an upgraded version of DECENT with better integration bound
and starting values. This version will be uploaded to GitHub within a week.
If you could not wait that long, please give me your email address and I
will send you the latest version by email.

Kind regards,
Agus

**Comment by huqingtao2018** [comment]
Dear Agus,

Thanks for your reply. It will be great if you can send me the lastest version of software and your bioinformatics paper by email. My email address is huqingtao@nibs.ac.cn

My data is UMI count. I will use the latest version and do the filtering of genes(>3% non-zero and >6 non-zero count) before running it.

What about the "out of memory" problem, is it caused by the zero count problem or I need do other setup ?

May I ask a further question about your 2018 Nature Medicine paper? In the method part, it says "Here we performed differential expression (DE) analysis using the DECENT package (version 0.1.0) without spike-ins, with its default parameters. The DE analysis was performed using the combined data from the two samples, and we attempted to correct for possible batch effects by **including a dummy batch**". What does "by including a dummy batch" means? Did you do this by setting up some parameters in DECENT?

Thank you very much.
Best wishes.

Qingtao Hu

**Comment by limfuxing** [comment]
Dear Qingtao,
DECENT does require significant amount of memory and it is recommended to
use DECENT on a server/HPC. This is especially true when you have 10000
cells. In one of the example in our paper, we have ~7000 cells and for
this, we need to use HPC with 128 Gb RAM. May I know what is your computing
environment?

Re: dummy batch variable, this is achieved by specifying the *W *option in
decent as W=~batch, were batch is the variable that contains
batch information.

I hope this helps. I will send you the accepted paper and the improved
version tomorrow when I am back to office.

Regards,
Agus

**Comment by huqingtao2018** [comment]
Dear Agus,

Thank you very much for sending me the paper.

Following your instruction, I filterred genes before running DECENT. When I use genes expressed in >10% of all cells, DECENT run sucessfully for some of my data, and I'm still trying the left data. (The filter ">3% and >5 non-zero count" reported the same error "EM iteration 1 finished at 2019-06-05 20:16:17  Log-likelihood 0 ..."). I'm happy that it can give me DE gene list now.

My server has 256 GB RAM. I got out of memory problem sometimes and I guess it was caused by running two DECENT commands at the same time. Now I'm defining marker genes for all of my cell groups. The only thing is that I need wait for a long time to get all of the result, as I cannot define marker gene for multi-groups at the same time in case of out of memory problem.( My command is, decent(data.obs = umi, X = ~as.factor(cell.type),W = ~as.factor(batch), n.cores = 50), my data is 17 cell groups, 6000 genes, 8000 cells and it takes around 6h for defining marker gene for one group) If you have any suggestion to make it faster, please help me.

Sometimes closeAllConnections() is needed and I don't understand why,and I hope it will help.

Thank you.
Best wishes.

Qingtao Hu

**Comment by cz-ye** [comment]
Hi Qingtao,

The "errors" you got are possibly just messages reporting the likelihood after each iteration. Could you show a complete line? Is the log-likelihood 0?

What you had there is probably the normal running time for DECENT. Fitting a hierarchical model like this is intrinsically costly. Other models with no hierarchical architecture might be faster but probably less accurate. It is now a priority of our work to improve the speed by largely avoiding the integration steps. We hope to release a faster version soon.

Best,
Cz

**Comment by limfuxing** [comment]
Hi Qingtao,
I don't know how you have done the cells and genes filtering. But for sparse datasets, it is important the filtering is done nested so that the final data matrix satisfy the gene and cell filtering criterion. As an example if I want to filter so I only have cells with > 3% non-zero counts and all genes need to have > 5 counts, you need to do (here data.obs is the original count matrix and cell-type is your X variable):

#define selected cells
sel.cell <- colMeans(data.obs>0)> 0.03
#select genes with > 5 nonzero among selected cells
data.obs <- data.obs[rowSums(data.obs[,sel.cell]>0)>5,]
#decent command: it's important to subset X and W for only selected cells
res <- decent(data.obs, X=~ X[sel.cell],W=~batch[sel.cell])

As Cz pointed out, DECENT is very accurate but there's a price to pay for it. We are currently working to speed-up the computation that would avoid the lengthy integration steps.

**Comment by huqingtao2018** [comment]
> 
> 
> Hi Qingtao,
> 
> The "errors" you got are possibly just messages reporting the likelihood after each iteration. Could you show a complete line? Is the log-likelihood 0?
> 
> What you had there is probably the normal running time for DECENT. Fitting a hierarchical model like this is intrinsically costly. Other models with no hierarchical architecture might be faster but probably less accurate. It is now a priority of our work to improve the speed by largely avoiding the integration steps. We hope to release a faster version soon.
> 
> Best,
> Cz

Dear Cz,

The complete error message is as follow,

No-DE model fitting started at 2019-06-09 09:22:28
EM iteration 1 finished at 2019-06-09 09:38:56  Log-likelihood: 0
EM iteration 2 finished at 2019-06-09 09:50:24  Log-likelihood: 0
EM iteration 3 finished at 2019-06-09 10:02:57  Log-likelihood: 0
EM iteration 4 finished at 2019-06-09 10:10:46  Log-likelihood: 0
EM iteration 5 finished at 2019-06-09 10:18:39  Log-likelihood: 0
EM iteration 6 finished at 2019-06-09 10:26:49  Log-likelihood: 0
Error in if ((loglik.vec[iter] - loglik.vec[iter - 1])/abs(loglik.vec[iter -  :
  missing value where TRUE/FALSE needed
Calls: decent -> fitNoDE
Execution halted

When I filter genes using " data.obs <- data.obs[rowMeans(data.obs[,sel.cell]>0)>0.1,]", it can run smoothly. The filter " data.obs <- data.obs[rowSums(data.obs[,sel.cell]>0)>5,]" will report the above error.

**Comment by cz-ye** [comment]
This has been fixed in the new version.
