### ISSUE TITLE
s.imputed and E.imputed error

### ISSUE THREAD

**Issue by huqingtao2018** [cz-ye/DECENT#6]
hi,

I can get result using the "sim" dataset, but when I set s.imputed=T or E.imputed=T, it reported error as below, would you please help me about this?  Thank you very much.

de.table <- decent(data.obs=sim$data.obs, X=~as.factor(sim$cell.type), n.cores=50, s.imputed=T, E.imputed=T)
error message:
"Likelihood ratio test finished at 2019-06-07 10:29:19
Error in e$fun(obj, substitute(ex), parent.frame(), e$data) :
  worker initialization failed: there is no package called 'DECENT2'
In addition: There were 13 warnings (use warnings() to see them)"

Best wishes.
Qingtao Hu

**Comment by cz-ye** [comment]
Hi Qingtao,

Thanks for your interest in our package. I have updated a new version. This should be fixed now.

Best,
Cz

**Comment by huqingtao2018** [comment]
Dear Cz,

I update to the new version, and I run the same command  it report the following error. 

Running in parallel, 50 cores used.
No-DE model fitting started at 2019-06-08 10:27:09
Error in serialize(data, node$con) : ignoring SIGPIPE signal
Calls: decent ... postNode -> sendData -> sendData.SOCKnode -> serialize
Execution halted
Warning message:
system call failed: Cannot allocate memory

I don't think it is cause by computer memory, because the same dataset can run successfully using the previous version of DECENT(withiout s.imputed=T and E.imputed=T). Would you please help me about this?

Best wishes.
Qingtao Hu.

**Comment by limfuxing** [comment]
Hi Qingtao,
Did the EM and LRT step finished with the new version?
If it does not finish, then I think the problems lies with the new codes that we uploaded yesterday calculated extra terms in the M-step to make it more accurate. I think these extra terms take additional memory that causes DECENT to crash. I have now put back the older version of the codes. Please re-install now and let me know if the problem persists. Thanks for patience.

**Comment by cz-ye** [comment]
This memory issue has been solved in the new version.
